package kann0200;

import java.util.ArrayList;
import java.util.Set;
import java.util.UUID;

import spacesettlers.objects.AbstractObject;
import spacesettlers.objects.Asteroid;
import spacesettlers.objects.Ship;
import spacesettlers.simulator.Toroidal2DPhysics;
import spacesettlers.utilities.Position;


public class GAState {
	double distanceToNearestMineableAsteroid;
	Asteroid nearestMineableAsteroid;
	ArrayList<UUID> nextPosition;
	private UUID currentTarget;
	private int currentTime;
	
	
	public GAState(Toroidal2DPhysics space, Ship ship, int currtimestep, int lastupdate) {
		updateState(space, ship, lastupdate);
		this.currentTime = currtimestep;
	}



	public void updateState(Toroidal2DPhysics space, Ship ship, int lastTimestep) {
		Set<Asteroid> asteroids = space.getAsteroids();
		distanceToNearestMineableAsteroid = Integer.MAX_VALUE;
		double distance;

		this.nextPosition = new ArrayList<UUID>();
		lastTimestep = space.getCurrentTimestep();
		this.nextPosition = Vectoring.movementMap(space, Combat.nearestEnemy(space,ship), ship);
		this.nextPosition.remove(0);
		this.currentTarget = space.getObjectById(this.nextPosition.get(this.nextPosition.size() - 1)).getId();
	}

	
	/**
	 * Return the nearest asteroid (used for actions)
	 * 
	 * @return
	 */
	public UUID getTarget() {
		
		return this.currentTarget;
	}
	public UUID targetReached(){
		this.nextPosition.remove(0);
		return this.nextPosition.get(0);
	}
	public int stackSize(){
		return this.nextPosition.size();
	}
	/**
	 * Generated by eclipse - make sure you update this when you update the state (just use eclipse to regenerate it)
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		long temp;
		temp = Double.doubleToLongBits(distanceToNearestMineableAsteroid);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		return result;
	}


	/**
	 * Generated by eclipse - make sure you update this when you update the state (just use eclipse to regenerate it)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		GAState other = (GAState) obj;
		if (Double.doubleToLongBits(distanceToNearestMineableAsteroid) != Double
				.doubleToLongBits(other.distanceToNearestMineableAsteroid))
			return false;
		return true;
	}



}
